src/SoftwareLab.Web/ViewModels/ErrorViewModel.cs
namespace SoftwareLab.Web.ViewModels;

public class ErrorViewModel
{
  public string? RequestId { get; set; }

  public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

src/SoftwareLab.Web/ViewModels/ProjectViewModel.cs
using System.Collections.Generic;

namespace SoftwareLab.Web.ViewModels;

public class ProjectViewModel
{
  public int Id { get; set; }
  public string? Name { get; set; }
  public List<ToDoItemViewModel> Items = new();
}

src/SoftwareLab.Web/ViewModels/ToDoItemViewModel.cs
using SoftwareLab.Core.ProjectAggregate;

namespace SoftwareLab.Web.ViewModels;

public class ToDoItemViewModel
{
  public int Id { get; set; }
  public string? Title { get; set; }
  public string? Description { get; set; }
  public bool IsDone { get; private set; }

  public static ToDoItemViewModel FromToDoItem(ToDoItem item)
  {
    return new ToDoItemViewModel()
    {
      Id = item.Id,
      Title = item.Title,
      Description = item.Description,
      IsDone = item.IsDone
    };
  }
}

src/SoftwareLab.Web/Controllers/BaseApiController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;

namespace SoftwareLab.Web.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public abstract class BaseApiController : ControllerBase
        {
            private IMediator _mediator;
            protected IMediator Mediator => _mediator ??= HttpContext.RequestServices.GetService<IMediator>();
        }
    
}

src/SoftwareLab.Web/Controllers/HomeController.cs
using System.Diagnostics;
using SoftwareLab.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace SoftwareLab.Web.Controllers;

/// <summary>
/// A sample MVC controller that uses views.
/// Razor Pages provides a better way to manage view-based content, since the behavior, viewmodel, and view are all in one place,
/// rather than spread between 3 different folders in your Web project. Look in /Pages to see examples.
/// See: https://ardalis.com/aspnet-core-razor-pages-%E2%80%93-worth-checking-out/
/// </summary>
public class HomeController : Controller
{
  public IActionResult Index()
  {
    return View();
  }

  [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
  public IActionResult Error() => View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
}

src/SoftwareLab.Web/Controllers/ProjectController.cs
using SoftwareLab.Core.ProjectAggregate;
using SoftwareLab.Core.ProjectAggregate.Specifications;
using SoftwareLab.SharedKernel.Interfaces;
using SoftwareLab.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace SoftwareLab.Web.Controllers;

[Route("[controller]")]
public class ProjectController : Controller
{
  private readonly IRepository<Project> _projectRepository;

  public ProjectController(IRepository<Project> projectRepository)
  {
    _projectRepository = projectRepository;
  }

  // GET project/{projectId?}
  [HttpGet("{projectId:int}")]
  public async Task<IActionResult> Index(int projectId = 1)
  {
    var spec = new ProjectByIdWithItemsSpec(projectId);
    var project = await _projectRepository.FirstOrDefaultAsync(spec);
    if (project == null)
    {
      return NotFound();
    }

    var dto = new ProjectViewModel
    {
      Id = project.Id,
      Name = project.Name,
      Items = project.Items
                    .Select(item => ToDoItemViewModel.FromToDoItem(item))
                    .ToList()
    };
    return View(dto);
  }
}

src/SoftwareLab.Web/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using SoftwareLab.Core.Features.User.Command.CreateUser;
using SoftwareLab.Core.Features.User.Query.GetUserById;
using SoftwareLab.Web.Controllers;

namespace SoftwareLab.WebAPI.Controllers
{
  public class UserController : BaseApiController
  {
    [HttpPost(Name = "CreateUser")]
    public async Task<int> CreateUser(CreateUserCommand createUserCommand)
    {
      return await Mediator.Send(createUserCommand);
    }
    [HttpGet(Name = "GetUserById")]
    public async Task<GetUserByIdViewModel> GetUserById(int id)
    {
      return await Mediator.Send(new GetUserByIdQuery { Id = id });
    }
  }
}

src/SoftwareLab.Web/Pages/ProjectDetails/Incomplete.cshtml.cs
using SoftwareLab.Core.ProjectAggregate;
using SoftwareLab.Core.ProjectAggregate.Specifications;
using SoftwareLab.SharedKernel.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SoftwareLab.Web.Pages.ProjectDetails;

public class IncompleteModel : PageModel
{
  private readonly IRepository<Project> _repository;

  [BindProperty(SupportsGet = true)]
  public int ProjectId { get; set; }

  public List<ToDoItem>? ToDoItems { get; set; }

  public IncompleteModel(IRepository<Project> repository)
  {
    _repository = repository;
  }

  public async Task OnGetAsync()
  {
    var projectSpec = new ProjectByIdWithItemsSpec(ProjectId);
    var project = await _repository.FirstOrDefaultAsync(projectSpec);
    if (project == null)
    {
      return;
    }

    var spec = new IncompleteItemsSpec();

    ToDoItems = spec.Evaluate(project.Items).ToList();
  }
}

src/SoftwareLab.Web/Pages/ProjectDetails/Index.cshtml.cs
using SoftwareLab.Core.ProjectAggregate;
using SoftwareLab.Core.ProjectAggregate.Specifications;
using SoftwareLab.SharedKernel.Interfaces;
using SoftwareLab.Web.ApiModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SoftwareLab.Web.Pages.ProjectDetails;

public class IndexModel : PageModel
{
  private readonly IRepository<Project> _repository;

  [BindProperty(SupportsGet = true)]
  public int ProjectId { get; set; }

  public string Message { get; set; } = "";

  public ProjectDTO? Project { get; set; }

  public IndexModel(IRepository<Project> repository)
  {
    _repository = repository;
  }

  public async Task OnGetAsync()
  {
    var projectSpec = new ProjectByIdWithItemsSpec(ProjectId);
    var project = await _repository.FirstOrDefaultAsync(projectSpec);
    if (project == null)
    {
      Message = "No project found.";

      return;
    }

    Project = new ProjectDTO
    (
        id: project.Id,
        name: project.Name,
        items: project.Items
        .Select(item => ToDoItemDTO.FromToDoItem(item))
        .ToList()
    );
  }
}

src/SoftwareLab.Web/Pages/ProjectDetails/Incomplete.cshtml
@page
@model SoftwareLab.Web.Pages.ProjectDetails.IncompleteModel

@{
    ViewData["Title"] = "Incomplete To Do Items (Razor Page)";
}

<h2>Incomplete To Do Items (Razor Page)</h2>
<ul>
    @if (Model.ToDoItems != null)
    {
        @foreach (var item in Model.ToDoItems)
        {
            <li>
                @item.Title
                @if (item.IsDone)
                {
                    <span>DONE!</span>
                }
                else
                {
                    <span>NOT DONE</span>
                }
                <br/>@item.Description
            </li>
        }
    }
</ul>

src/SoftwareLab.Web/Pages/ProjectDetails/Index.cshtml
@page "{ProjectId}"
@model SoftwareLab.Web.Pages.ProjectDetails.IndexModel

@{
    ViewData["Title"] = "Project Details (Razor Page)";
}

@if (!String.IsNullOrEmpty(Model.Message))
{
    <h2>@Model.Message</h2>
}
else
{

<h2>Project (Razor Page)</h2>

<h3>Name: @Model.Project?.Name</h3>

<b>Items:</b>

    <ul>
        @if (Model.Project != null)
        {
            @foreach (var item in Model.Project.Items)
            {
                <li>
                    @item.Title
                    @if (item.IsDone)
                    {
                        <span>DONE!</span>
                    }
                    else
                    {
                        <span>NOT DONE</span>
                    }
                    <br/>@item.Description
                </li>
            }
        }
    </ul>
}

src/SoftwareLab.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Clean DDD Architecture Sample";
}
<div class="row">
    <div class="col-md-4">
        <h3>Using this template</h3>
        <p>
            This template includes support for:
            <ul>
                <li>APIs using API Endpoints (in the /Endpoints folder)</li>
                <li>APIs using Controllers (in the /Api and /ApiModels folders)</li>
                <li>Pages using Razor Pages (in the /Pages folder and /Views/Shared folder)</li>
                <li>Pages using Controllers and Views (in the /Controllers, /ViewModels, and /Views folders - keep /Views/Shared for Razor Pages though)</li>
            </ul>
            Choose which features you will use for your project and delete the ones you will not use.
        </p>
        <p>
            Provide feedback and report issues in the <a href="https://github.com/ardalis/CleanArchitecture">project's GitHub repository</a>; ask questions using the <a href="https://stackoverflow.com/questions/tagged/ardalis-cleanarchitecture?tab=Newest">ardalis-cleanarchitecture tag on StackOverflow</a>.
        </p>
    </div>
    <div class="col-md-4">
        <h3>APIs</h3>
        Shows both Controller and Endpoint APIs.
        <ul>
            <li><a href="/swagger">API Documentation (Swagger)</a></li>
        </ul>
        <h3>Projects (using Razor Pages)</h3>
        <ul>
            <li><a asp-page="/ProjectDetails/Index" asp-route-ProjectId="1">Show Project ID:1 and its To Do Items</a></li>
            <li><a asp-page="/ProjectDetails/Incomplete">List Incomplete To Do Items</a></li>
        </ul>
        <h3>Projects (using MVC Views)</h3>
        <ul>
            <li><a asp-area="" asp-controller="Project" asp-action="Index" asp-route-projectId="1">Show Project ID:1 and its To Do Items</a></li>
        </ul>
    </div>
    <div class="col-md-4">
        <h3>About the Author</h3>
        <ul>
            <li><a href="https://ardalis.com">Blog - Ardalis.com</a></li>
            <li><a href="https://twitter.com/ardalis">Twitter - @@ardalis</a></li>
            <li><a href="https://github.com/ardalis">GitHub</a></li>
            <li><a href="https://www.pluralsight.com/authors/steve-smith">Latest Pluralsight Courses</a></li>
        </ul>
        <h3>More resources for this template</h3>
        <ul>
            <li><a href="https://github.com/ardalis/CleanArchitecture">CleanArchitecture GitHub repository</a></li>
            <li><a href="https://stackoverflow.com/questions/tagged/ardalis-cleanarchitecture?tab=Newest">Ardalis-CleanArchitecture on Stack Overflow</a></li>
            <li><a href="https://www.pluralsight.com/courses/domain-driven-design-fundamentals">Domain-Driven Design Fundamentals Course (Pluralsight)</a></li>
            <li><a href="https://www.pluralsight.com/courses/n-tier-apps-part1">Creating N-Tier Applications in C# Course (Part 1) (Pluralsight)</a></li>
            <li><a href="https://www.pluralsight.com/courses/n-tier-csharp-part2">Creating N-Tier Applications in C# Course (Part 2) (Pluralsight)</a></li>
        </ul>
    </div>
</div>

src/SoftwareLab.Web/Views/Project/Index.cshtml
@{
    ViewData["Title"] = "Project Details";
}
@model SoftwareLab.Web.ViewModels.ProjectViewModel
<h2>Project (MVC View)</h2>

<h3>Name: @Model?.Name</h3>

<b>Items:</b>

<ul>
    @if (Model?.Items != null)
    {
        @foreach (var item in Model.Items)
        {
            <li>@item.Title<br/>@item.Description</li>
        }
    }
</ul>

src/SoftwareLab.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - SoftwareLab.Web</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/SoftwareLab.Web.styles.css" asp-append-version="true" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SoftwareLab.Web</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>
	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; @DateTime.Today.Year - SoftwareLab.Web
		</div>
	</footer>

	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>